[env]
MISE_ENV="dev"

[tasks.hygiene]
description = "Code hygiene (pre-commit hooks)"
run = ["pre-commit run --all-files"]

[tasks.install]
depends = ["pre-commit:install"]
description = "Install dependencies"

[tasks."pre-commit:install"]
description = "Install pre-commit hooks"
run = [
    "pre-commit install",
    "pre-commit install --hook-type pre-commit",
    "pre-commit install --hook-type commit-msg",
]

[tasks."pre-commit:autoupdate"]
description = "Auto update pre-commit hooks"
run = ["pre-commit autoupdate"]

[tools]
"python" = "3.13"
"pipx:pre-commit" = "4.2.0"
"ubi:koalaman/shellcheck" = "0.10.0"
"aqua:cocogitto/cocogitto" = "6.3.0"
"aqua:aquasecurity/trivy" = "0.61.0"
"aqua:cli/cli" = "2.69.0"
