---
name: ci-conventional-commits
on: [push] # yamllint disable-line rule:truthy
jobs:
  cog-check-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Conventional Commits Check
        uses: cocogitto/cocogitto-action@v3
        with:
          release: true
          git-user: 'Cocogitto'
          git-user-email: 'bot@cocogitto.io'
